### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by julkue** [helpers/handlebars-helper-repeat#7]
When having a repeat of 10 inside a repeat of 3 (so total 30) the following error is printed:

![topic](https://user-images.githubusercontent.com/8310677/37823408-abf98088-2e89-11e8-920e-a1e37fc6be0f.png)

**Comment by doowb** [comment]
Hi @julmot, can you add additional information? Like your context, templates, and code used to render the templates? If you have a minimum reproducible repository to look at, that would be even better.
